export interface Proyecto {
  slug: string;
  titulo: string;
  descripcion: string;
  detalles: string[];
  hero: string;
  imagenes: string[];
}

export const proyectos: Proyecto[] = [
  {
    slug: 'casa-jj',
    titulo: 'CASA JJ',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      'Barrio: Estancias de Pilar - Pilar, Prov. de Buenos Aires',
      '275 m2',
      'Vivienda unifamiliar',
    ],
    hero: '/CASA-JJ-0.jpg',
    imagenes: [
      '/CASA-JJ-1.jpg',
      '/CASA-JJ-2.jpg',
      '/CASA-JJ-3.jpg',
      '/CASA-JJ-4.jpg',
      '/CASA-JJ-5.jpg',
      '/CASA-JJ-6.jpg',
      '/CASA-JJ-7.jpg',
      '/CASA-JJ-8.jpg',
      '/CASA-JJ-9.jpg',
      '/CASA-JJ-10.jpg',
      '/CASA-JJ-11.jpg',
      '/CASA-JJ-12.jpg',
      '/CASA-JJ-13.jpg',
      '/CASA-JJ-14.jpg',
      '/CASA-JJ-15.jpg',
      '/CASA-JJ-16.jpg',
      '/CASA-JJ-17.jpg',
      '/CASA-JJ-18.jpg',
    ],
  },
  {
    slug: 'casa-jm',
    titulo: 'CASA JM',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      'Barrio: El Ocho - Pilar, Prov. de Buenos Aires',
      '301 m2',
      'Vivienda unifamiliar',
    ],
    hero: '/CASA-JM-0.jpg',
    imagenes: [
      '/CASA-JM-1.jpg',
      '/CASA-JM-2.jpg',
      '/CASA-JM-3.jpg',
      '/CASA-JM-4.jpg',
      '/CASA-JM-5.jpg',
      '/CASA-JM-6.jpg',
      '/CASA-JM-7.jpg',
      '/CASA-JM-8.jpg',
      '/CASA-JM-9.jpg',
      '/CASA-JM-10.jpg',
      '/CASA-JM-11.jpg',
      '/CASA-JM-12.jpg',
      '/CASA-JM-13.jpg',
      '/CASA-JM-14.jpg',
      '/CASA-JM-15.jpg',
      '/CASA-JM-16.jpg',
      '/CASA-JM-17.jpg',
      '/CASA-JM-18.jpg',
      '/CASA-JM-19.jpg',
      '/CASA-JM-20.jpg',
      '/CASA-JM-21.jpg',
      '/CASA-JM-22.jpg',
      '/CASA-JM-23.jpg',
      '/CASA-JM-24.jpg',
      '/CASA-JM-25.jpg',
      '/CASA-JM-26.jpg',
      '/CASA-JM-27.jpg',
      '/CASA-JM-28.jpg',
      '/CASA-JM-29.jpg',
      '/CASA-JM-30.jpg',
      '/CASA-JM-31.jpg',
      '/CASA-JM-32.jpg',
    ],
  },
  {
    slug: 'casa-golf',
    titulo: 'CASA GOLF',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      'Barrio: Estancia Villa Maria - Máximo Paz, Prov. de Buenos Aires',
      '442 m2',
      'Vivienda unifamiliar',
    ],
    hero: '/CASAGOLFRENDER-003.JPG',
    imagenes: [
      '/CASAGOLFRENDER-004.JPG',
      '/CASAGOLFRENDER-005.JPG',
      '/CASAGOLFRENDER-006.JPG',
      '/CASAGOLFRENDER-007.JPG',
      '/CASAGOLFRENDER-008.JPG',
      '/CASAGOLFRENDER-009.JPG',
      '/CASAGOLF-002.jpeg',
      '/CASAGOLF-003.jpeg',
      '/CASAGOLF-004.jpeg',
      '/CASAGOLF-008.jpeg',
      '/CASAGOLF-009.jpeg',
      '/CASAGOLF-023.jpeg',
      '/CASAGOLF-029.jpeg',
      '/CASAGOLF-031.jpeg',
      '/CASAGOLF-032.jpeg',
      '/CASAGOLF-034.jpeg',
      '/CASAGOLF-035.jpeg',
      '/CASAGOLF-039.jpeg',
      '/CASAGOLF-040.jpeg',
      '/CASAGOLF-042.jpeg',
      '/CASAGOLF-046.jpeg',
      '/CASAGOLF-047.jpeg',
      '/CASAGOLFRENDER-001.JPEG',
    ],
  },
  {
    slug: 'casa-sj',
    titulo: 'CASA SJ - OBRA EN PROCESO',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      'Barrio: Medal C.C. - Pilar, Prov. de Buenos Aires',
      '255 m2',
      'Vivienda unifamiliar',
    ],
    hero: '/CASA SJ-0.png',
    imagenes: [
      '/CASA SJ-1.png',
    ],
  },
  {
    slug: 'casa-bg',
    titulo: 'CASA BG - OBRA EN PROCESO',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      'Barrio: El Tropezón - San Antonio de Areco, Prov. de Buenos Aires',
      '260 m2',
      'Vivienda unifamiliar',
    ],
    hero: '/CASA-BG-0.png',
    imagenes: [
      '/CASA-BG-1.png',
    ],
  },
  {
    slug: 'casa-rz',
    titulo: 'CASA RZ',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      'Barrio: El Ocho - Pilar, Prov. de Buenos Aires',
      '260 m2',
      'Vivienda unifamiliar',
    ],
    hero: '/CASA-RZ-0.jpeg',
    imagenes: [
      '/CASA-RZ-1.jpeg',
      '/CASA-RZ-2.jpeg',
      '/CASA-RZ-3.jpeg',
      '/CASA-RZ-4.jpeg',
      '/CASA-RZ-5.jpeg',
      '/CASA-RZ-6.jpeg',
      '/CASA-RZ-7.jpeg',
      '/CASA-RZ-8.jpeg',
      '/CASA-RZ-9.jpeg',
      '/CASA-RZ-10.jpeg',
      '/CASA-RZ-11.jpeg',
      '/CASA-RZ-12.jpeg',
      '/CASA-RZ-13.jpeg',
      '/CASA-RZ-14.jpeg',
      '/CASA-RZ-15.jpeg',
      '/CASA-RZ-16.jpeg',
      '/CASA-RZ-17.jpeg',
      '/CASA-RZ-18.jpeg',
      '/CASA-RZ-19.jpeg',
      '/CASA-RZ-20.jpeg',
    ],
  },
  {
    slug: 'casa-g',
    titulo: 'CASA G',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      'Barrio: Estancias de Pilar - Pilar, Prov. de Buenos Aires',
      '324 m2',
      'Vivienda unifamiliar',
    ],
    hero: '/CASA-G-0.jpg',
    imagenes: [
      '/CASA-G-1.JPEG',
      '/CASA-G-2.JPEG',
      '/CASA-G-3.JPEG',
      '/CASA-G-4.JPEG',
      '/CASA-G-5.jpeg',
      '/CASA-G-6.JPEG',
      '/CASA-G-7.jpg',
      '/CASA-G-8.jpeg',
      '/CASA-G-9.JPEG',
      '/CASA-G-10.JPEG',
      '/CASA-G-11.JPEG',
      '/CASA-G-12.jpeg',
      '/CASA-G-13.JPEG',
      '/CASA-G-14.JPEG',
      '/CASA-G-15.jpg',
      '/CASA-G-16.JPEG',
      '/CASA-G-17.jpg',
    ],
  },
  {
    slug: 'casa-cs',
    titulo: 'CASA CS',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      'Barrio: Estancia Villa Maria - Máximo Paz, Prov. de Buenos Aires',
      '210 m2',
      'Vivienda unifamiliar',
    ],
    hero: '/CASACS-002.jpg',
    imagenes: [
      '/CASACS-002.jpg',
      '/CASACS-003.jpg',
      '/CASACS-005.jpg',
      '/CASACS-008.jpeg',
      '/CASACS-009.jpg',
      '/CASACS-010.jpg',
      '/CASACS-011.jpg',
      '/CASACS-012.jpg',
      '/CASACS-013.jpg',
      '/CASACS-014.jpg',
      '/CASACS-015.jpg',
      '/CASACS-016.jpg',
      '/CASACS-001.jpg',
      '/CASACS-004.jpg',
      '/CASACS-006.jpg',
      '/CASACS-007.jpg',
    ],
  },
  {
    slug: 'reforma-callao',
    titulo: 'REFORMA CALLAO',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Recoleta, Ciudad Autónoma de Buenos Aires',
    ],
    hero: '/RF-CALLAO-0.jpg',
    imagenes: [
      '/RF-CALLAO-1.JPEG',
      '/RF-CALLAO-2.jpg',
      '/RF-CALLAO-3.jpg',
      '/RF-CALLAO-4.jpg',
      '/RF-CALLAO-5.jpg',
      '/RF-CALLAO-6.JPEG',
      '/RF-CALLAO-7.JPEG',
      '/RF-CALLAO-8.JPEG',
    ],
  },
  {
    slug: 'reforma-talcahuano',
    titulo: 'REFORMA TALCAHUANO',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Recoleta, Ciudad Autónoma de Buenos Aires',
    ],
    hero: '/RF-TALCAHUANO-0.JPEG',
    imagenes: [
      '/RF-TALCAHUANO-1.JPEG',
      '/RF-TALCAHUANO-2.JPEG',
      '/RF-TALCAHUANO-3.JPEG',
      '/RF-TALCAHUANO-4.JPEG',
      '/RF-TALCAHUANO-5.JPEG',
      '/RF-TALCAHUANO-6.JPEG',
      '/RF-TALCAHUANO-7.JPEG',
      '/RF-TALCAHUANO-8.JPEG',
    ],
  },
  {
    slug: 'reforma-arcos',
    titulo: 'REFORMA ARCOS',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Belgrano, Ciudad Autónoma de Buenos Aires',
    ],
    hero: '/RF-ARCOS-0.JPEG',
    imagenes: [
      '/RF-ARCOS-1.JPEG',
      '/RF-ARCOS-2.JPEG',
      '/RF-ARCOS-3.JPEG',
      '/RF-ARCOS-4.JPEG',
      '/RF-ARCOS-5.JPEG',
      '/RF-ARCOS-6.JPEG',
      '/RF-ARCOS-7.JPEG',
      '/RF-ARCOS-8.JPEG',
    ],
  },
  {
    slug: 'reforma-ayacucho',
    titulo: 'REFORMA AYACUCHO',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Recoleta, Ciudad Autónoma de Buenos Aires',
    ],
    hero: '/RF-AYACUCHO-0.jpg',
    imagenes: [
      '/RF-AYACUCHO-1.jpg',
      '/RF-AYACUCHO-2.jpg',
      '/RF-AYACUCHO-3.jpg',
      '/RF-AYACUCHO-4.jpg',
      '/RF-AYACUCHO-5.jpg',
      '/RF-AYACUCHO-6.jpg',
      '/RF-AYACUCHO-7.jpg',
      '/RF-AYACUCHO-8.jpg',
    ],
  },
  {
    slug: 'reforma-pena-a',
    titulo: 'REFORMA PEÑA',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Recoleta, Ciudad Autónoma de Buenos Aires',
    ],
    hero: '/RF-PEÑA-0.jpg',
    imagenes: [
      '/RF-PEÑA-1.jpg',
      '/RF-PEÑA-2.jpg',
      '/RF-PEÑA-3.jpg',
      '/RF-PEÑA-4.jpg',
      '/RF-PEÑA-5.jpg',
      '/RF-PEÑA-6.jpg',
    ],
  },
  // PROYECTOS OCULTOS - Se mostrarán más adelante
  // {
  //   slug: 'casa-pm',
  //   titulo: 'CASA PM',
  //   descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
  //   detalles: [
  //     'Barrio: Estancia Villa Maria - Máximo Paz, Prov. de Buenos Aires',
  //     '360 m2',
  //     'vivienda unifamiliar',
  //   ],
  //   hero: '/hero-image.jpg',
  //   imagenes: [],
  // },
  // {
  //   slug: 'casa-ab',
  //   titulo: 'CASA AB',
  //   descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
  //   detalles: [
  //     'Barrio: Estancia Villa Maria - Máximo Paz, Prov. de Buenos Aires',
  //     '360 m2',
  //     'vivienda unifamiliar',
  //   ],
  //   hero: '/hero-image.jpg',
  //   imagenes: [],
  // },
  // {
  //   slug: 'casa-fc',
  //   titulo: 'CASA FC',
  //   descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
  //   detalles: [
  //     'Barrio: Estancia Villa Maria - Máximo Paz, Prov. de Buenos Aires',
  //     '363 m2',
  //     'vivienda unifamiliar',
  //   ],
  //   hero: '/hero-image.jpg',
  //   imagenes: [],
  // },
  // {
  //   slug: 'casa-valeria',
  //   titulo: 'CASA VALERIA',
  //   descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
  //   detalles: [
  //     'Barrio: Estancia Villa Maria - Máximo Paz, Prov. de Buenos Aires',
  //     '215 m2',
  //     'vivienda unifamiliar',
  //   ],
  //   hero: '/hero-image.jpg',
  //   imagenes: [],
  // },
  // {
  //   slug: 'reforma-scalabrini',
  //   titulo: 'REFORMA SCALABRINI ORTIZ',
  //   descripcion: 'REFORMA INTEGRAL',
  //   detalles: [
  //     'Recoleta, Ciudad Autónoma de Buenos Aires',
  //   ],
  //   hero: '/casa-dd-hero.jpg',
  //   imagenes: ['/casa-dd-hero.jpg'],
  // },
  // {
  //   slug: 'reforma-junin',
  //   titulo: 'REFORMA JUNIN',
  //   descripcion: 'REFORMA INTEGRAL',
  //   detalles: [
  //     'Recoleta, Ciudad Autónoma de Buenos Aires',
  //   ],
  //   hero: '/hero-image.jpg',
  //   imagenes: [],
  // },
  // {
  //   slug: 'reforma-tagle',
  //   titulo: 'REFORMA TAGLE',
  //   descripcion: 'REFORMA INTEGRAL',
  //   detalles: [
  //     'Recoleta, Ciudad Autónoma de Buenos Aires',
  //   ],
  //   hero: '/hero-image.jpg',
  //   imagenes: [],
  // },
]; 