export interface Proyecto {
  slug: string;
  titulo: string;
  descripcion: string;
  detalles: string[];
  hero: string;
  imagenes: string[];
}

export const proyectos: Proyecto[] = [
  {
    slug: 'casa-jj',
    titulo: 'CASA JJ',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      '228m² cubiertos - 59m² semicubiertos',
      'Estancias de Pilar, Pilar, Pcia. de Buenos Aires',
      '2022',
    ],
    hero: '/CASAJJ-020.jpg',
    imagenes: [
      '/CASAJJ-001.jpg',
      '/CASAJJ-002.jpg',
      '/CASAJJ-003.jpg',
      '/CASAJJ-005.jpg',
      '/CASAJJ-007.jpg',
      '/CASAJJ-010.jpg',
      '/CASAJJ-012.jpg',
      '/CASAJJ-017.jpg',
      '/CASAJJ-022.jpg',
      '/CASAJJ-004.jpg',
      '/CASAJJ-006.jpg',
      '/CASAJJ-008.jpg',
      '/CASAJJ-009.jpg',
      '/CASAJJ-011.jpg',
      '/CASAJJ-013.jpg',
      '/CASAJJ-014.jpg',
      '/CASAJJ-015.jpg',
      '/CASAJJ-016.jpg',
      '/CASAJJ-018.jpg',
      '/CASAJJ-019.jpg',
      '/CASAJJ-020.jpg',
      '/CASAJJ-021.jpg',
    ],
  },
  {
    slug: 'casa-jm',
    titulo: 'CASA JM',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      '228m² cubiertos - 59m² semicubiertos',
      'Estancias de Pilar, Pilar, Pcia. de Buenos Aires',
      '2022',
    ],
    hero: '/CASAJM-041.jpg',
    imagenes: [
      '/CASAJM-044.jpg',
      '/CASAJM-024.jpg',
      '/CASAJM-028.jpg',
      '/CASAJM-021.jpg',
      '/CASAJM-009.jpg',
      '/CASAJM-017.jpg',
      '/CASAJM-038.jpg',
      '/CASAJM-039.jpg',
      '/CASAJM-040.jpg',
      '/CASAJM-027.jpg',
      '/CASAJM-032.jpg',
      '/CASAJM-001.jpg',
      '/CASAJM-003.jpg',
      '/CASAJM-004.jpg',
      '/CASAJM-005.jpg',
    ],
  },
  {
    slug: 'casa-golf',
    titulo: 'CASA GOLF',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      '228m² cubiertos - 59m² semicubiertos',
      'Estancias de Pilar, Pilar, Pcia. de Buenos Aires',
      '2022',
    ],
    hero: '/CASAGOLFRENDER-003.JPG',
    imagenes: [
      '/CASAGOLFRENDER-004.JPG',
      '/CASAGOLFRENDER-005.JPG',
      '/CASAGOLFRENDER-006.JPG',
      '/CASAGOLFRENDER-007.JPG',
      '/CASAGOLFRENDER-008.JPG',
      '/CASAGOLFRENDER-009.JPG',
      '/CASAGOLF-002.jpeg',
      '/CASAGOLF-003.jpeg',
      '/CASAGOLF-004.jpeg',
      '/CASAGOLF-008.jpeg',
      '/CASAGOLF-009.jpeg',
      '/CASAGOLF-023.jpeg',
      '/CASAGOLF-029.jpeg',
      '/CASAGOLF-031.jpeg',
      '/CASAGOLF-032.jpeg',
      '/CASAGOLF-034.jpeg',
      '/CASAGOLF-035.jpeg',
      '/CASAGOLF-039.jpeg',
      '/CASAGOLF-040.jpeg',
      '/CASAGOLF-042.jpeg',
      '/CASAGOLF-046.jpeg',
      '/CASAGOLF-047.jpeg',
      '/CASAGOLFRENDER-001.JPEG',
    ],
  },
  {
    slug: 'casa-bg',
    titulo: 'CASA BG',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      '228m² cubiertos - 59m² semicubiertos',
      'Estancias de Pilar, Pilar, Pcia. de Buenos Aires',
      '2022',
    ],
    hero: '/casa-jj-4.jpg',
    imagenes: ['/casa-jj-4.jpg'],
  },
  {
    slug: 'casa-cs',
    titulo: 'CASA CS',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      '200m² cubiertos - 60m² semicubiertos',
      'Barrio cerrado, Pilar, Pcia. de Buenos Aires',
      '2023',
    ],
    hero: '/CASACS-002.jpg',
    imagenes: [
      '/CASACS-002.jpg',
      '/CASACS-003.jpg',
      '/CASACS-005.jpg',
      '/CASACS-008.jpeg',
      '/CASACS-009.jpg',
      '/CASACS-010.jpg',
      '/CASACS-011.jpg',
      '/CASACS-012.jpg',
      '/CASACS-013.jpg',
      '/CASACS-014.jpg',
      '/CASACS-015.jpg',
      '/CASACS-016.jpg',
      '/CASACS-001.jpg',
      '/CASACS-004.jpg',
      '/CASACS-006.jpg',
      '/CASACS-007.jpg',
    ],
  },
  {
    slug: 'casa-rz',
    titulo: 'CASA RZ',
    descripcion: 'PROYECTO, DIRECCIÓN Y CONSTRUCCIÓN',
    detalles: [
      '250m² cubiertos - 80m² semicubiertos',
      'Barrio cerrado, Pilar, Pcia. de Buenos Aires',
      '2023',
    ],
    hero: '/CASARZ-A-002.jpeg',
    imagenes: [
      '/CASARZ-A-002.jpeg',
      '/CASARZ-B-001.jpeg',
      '/CASARZ-C-002.jpeg',
      '/CASARZ-C-004.jpeg',
      '/CASARZ-C-006.jpeg',
      '/CASARZ-C-007.jpeg',
      '/CASARZ-C-008.jpeg',
      '/CASARZ-C-009.jpeg',
      '/CASARZ-D-001.jpeg',
      '/CASARZ-E-004.jpeg',
      '/CASARZ-E-007.jpeg',
    ],
  },
  {
    slug: 'reforma-callao',
    titulo: 'REFORMA CALLAO',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Cocina, baño y dormitorios',
      'Estancias de Pilar, Pilar, Pcia. de Buenos Aires',
      '2022',
    ],
    hero: '/casa-jj-1.jpg',
    imagenes: ['/casa-jj-1.jpg'],
  },
  {
    slug: 'reforma-talcahuano',
    titulo: 'REFORMA TALCAHUANO',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Cocina, baño, living y espacios comunes',
      'Recoleta, CABA',
      '2023',
    ],
    hero: '/RFTALCAHUANO-004.JPEG',
    imagenes: [
      '/RFTALCAHUANO-001.JPEG',
      '/RFTALCAHUANO-002.JPEG',
      '/RFTALCAHUANO-003.JPEG',
      '/RFTALCAHUANO-004.JPEG',
      '/RFTALCAHUANO-005.JPEG',
      '/RFTALCAHUANO-006.JPEG',
      '/RFTALCAHUANO-007.JPEG',
      '/RFTALCAHUANO-008.JPEG',
      '/RFTALCAHUANO-009.JPEG',
      '/RFTALCAHUANO-010.JPEG',
      '/RFTALCAHUANO-011.JPEG',
      '/RFTALCAHUANO-012.JPEG',
      '/RFTALCAHUANO-013.JPEG',
      '/RFTALCAHUANO-014.JPEG',
    ],
  },
  {
    slug: 'reforma-arcos',
    titulo: 'REFORMA ARCOS',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Cocina, baño y espacios comunes',
      'Barrio Arcos, Pilar, Pcia. de Buenos Aires',
      '2023',
    ],
    hero: '/RFARCOS-004.JPEG',
    imagenes: [
      '/RFARCOS-001.JPEG',
      '/RFARCOS-002.JPEG',
      '/RFARCOS-003.JPEG',
      '/RFARCOS-004.JPEG',
      '/RFARCOS-005.JPEG',
      '/RFARCOS-006.JPEG',
      '/RFARCOS-007.JPEG',
      '/RFARCOS-008.JPEG',
      '/RFARCOS-009.JPEG',
      '/RFARCOS-010.JPEG',
      '/RFARCOS-011.JPEG',
      '/RFARCOS-012.JPEG',
    ],
  },
  {
    slug: 'reforma-ayacucho',
    titulo: 'REFORMA AYACUCHO',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Living, cocina, baño y espacios comunes',
      'Ayacucho, CABA',
      '2023',
    ],
    hero: '/RFAYACUCHO-010.jpg',
    imagenes: [
      '/RFAYACUCHO-001.jpg',
      '/RFAYACUCHO-002.jpg',
      '/RFAYACUCHO-003.jpg',
      '/RFAYACUCHO-004.jpg',
      '/RFAYACUCHO-005.jpg',
      '/RFAYACUCHO-006.jpg',
      '/RFAYACUCHO-007.jpg',
      '/RFAYACUCHO-008.jpg',
      '/RFAYACUCHO-009.jpg',
      '/RFAYACUCHO-010.jpg',
      '/RFAYACUCHO-011.jpg',
      '/RFAYACUCHO-012.jpg',
    ],
  },
  {
    slug: 'reforma-pena-a',
    titulo: 'REFORMA PEÑA A',
    descripcion: 'REFORMA INTEGRAL',
    detalles: [
      'Cocina, baño y espacios comunes',
      'Peña, CABA',
      '2023',
    ],
    hero: '/RFPEÑA-001.jpg',
    imagenes: [
      '/RFPEÑA-001.jpg',
      '/RFPEÑA-002.jpg',
      '/RFPEÑA-003.jpg',
      '/RFPEÑA-004.jpg',
      '/RFPEÑA-005.jpg',
      '/RFPEÑA-006.jpg',
      '/RFPEÑA-007.jpg',
    ],
  },
  {
    slug: 'reforma-scalabrini',
    titulo: 'REFORMA SCALABRINI',
    descripcion: 'REFORMA PARCIAL',
    detalles: [
      'Baño y cocina',
      'Estancias de Pilar, Pilar, Pcia. de Buenos Aires',
      '2022',
    ],
    hero: '/casa-dd-hero.jpg',
    imagenes: ['/casa-dd-hero.jpg'],
  },
]; 